### ISSUE TITLE
Compatibility with Diematic BUS

### ISSUE THREAD

**Issue by piotrC4** [ngraziano/isystem-to-mqtt#1]
I tested your code with other boiler - De Dietrich MC25 and Diematic 3 console. It have different Modbus addresses, for example:
"outside/temperature" - 7
"zone-a/day-target-temperature" - 14
"zone-a/night-target-temperature" - 15
"zone-a/mode" - 17
"zone-a/sensor-temperature" - 18
"zone-b/day-target-temperature" - 23
"zone-b/night-target-temperature" - 24

May good option is to parametrize READ/WRITE tables and read sequence with version of boiler?

**Comment by ngraziano** [comment]
I find an excel file on internet with address, and your address are also in this file http://www.domotique-fibaro.fr/index.php/topic/5677-de-dietrich-diematic-isystem/?p=126001   .  

But I make a modification dc89d231499b4f33a192231be275c0818f9cada1 to allow to have other tables, you only need to define a new model in get_tables() in tables.py.

**Comment by piotrC4** [comment]
Thanks for link to forum, it is very usefull. Model definition is ok. Thanks
